export const projects = [
  {
    id: 'project-01',
    title: 'Project 01',
    year: '2026',
    role: 'Brand Designer',
    services: 'Visual Identity / Art Direction / Layout System',
    color: '#f3b8b7',
    imageUrl: '/assets/01框.jpg',
    summary: '这里是第一个项目简介。后续可以替换成真实品牌项目的概念、目标、视觉方向和你的工作内容。',
    detail: '三级页面用于展开单个项目：可以放主视觉、品牌系统、过程图、延展物料、项目说明和你的角色。',
  },
  {
    id: 'project-02',
    title: 'Project 02',
    year: '2025',
    role: 'Visual Designer',
    services: 'Brand System / Editorial / Packaging',
    color: '#b9d9d1',
    imageUrl: '/poster/0b04e48af4ab021879f1903c5d897cb3.jpg',
    summary: '一个预留的作品入口，用于后续替换成真实项目封面和简介。',
    detail: '这里保留为项目详情占位内容。',
  },
  {
    id: 'project-03',
    title: 'Project 03',
    year: '2024',
    role: 'Art Director',
    services: 'Campaign / Key Visual / Digital',
    color: '#cbc6f0',
    imageUrl: '/poster/26aa5052559411d6c013afa44cbc06f7.jpg',
    summary: '走廊中的第三个作品入口，占位文本可后续替换。',
    detail: '这里保留为项目详情占位内容。',
  },
  {
    id: 'project-04',
    title: 'Project 04',
    year: '2024',
    role: 'Brand Designer',
    services: 'Identity / Typography / Motion',
    color: '#efd391',
    imageUrl: '/poster/45b447ae8763f048e2a9da413b08e9b8.jpg',
    summary: '走廊中的第四个作品入口，占位文本可后续替换。',
    detail: '这里保留为项目详情占位内容。',
  },
  {
    id: 'project-05',
    title: 'Project 05',
    year: '2023',
    role: 'Graphic Designer',
    services: 'Poster / Print / Exhibition',
    color: '#b9cde8',
    imageUrl: '/poster/55e5429e0aa7602700f5af9b2a161c7e.jpg',
    summary: '走廊中的第五个作品入口，占位文本可后续替换。',
    detail: '这里保留为项目详情占位内容。',
  },
  {
    id: 'project-06',
    title: 'Project 06',
    year: '2023',
    role: 'Designer',
    services: 'Concept / Identity / Web',
    color: '#d8d4ca',
    imageUrl: '/poster/61c64a5090ba19fa903271cca056a320.jpg',
    summary: '走廊中的第六个作品入口，占位文本可后续替换。',
    detail: '这里保留为项目详情占位内容。',
  },
];
